on:
    push:
      branches:
        - main
  
name: Build My Apps
  
jobs:
    build:
      name: Build and Release new apk
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-java@v2
          with:
            distribution: 'zulu'
            java-version: '11'
  
        - uses: subosito/flutter-action@v2
          with:
            channel: 'stable'
        - run: flutter pub get
        - run: flutter build apk --release --split-per-abi

        - name: Get Flutter app version
        id: get_version
        run: |
          version=$(grep '^version:' pubspec.yaml | cut -d ' ' -f 2)
          echo "VERSION=$version" >> $GITHUB_ENV
          echo "::set-output name=version::$version"
  
        - name: Push to Releases
          uses: ncipollo/release-action@v1
          with:
            artifacts: "build/app/outputs/apk/release/*"
            tag: v${{ steps.get_version.outputs.version }}
            token: ${{ secrets.TOKEN }}